In [1]:
import pandas as pd
dataset = pd.read_csv('/kaggle/input/50start123/50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
#Numpy dizilerine giriş

In [4]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [5]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [6]:
type(list1)

list

In [7]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1.data

In [10]:
arr1.dtype

dtype('int64')

In [11]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [15]:
arr1.nbytes

48

In [16]:
#Spesifik fonksiyonlar
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [19]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [20]:
#Sadece tekler
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
#Sadece çiftler
ar1 = np.arange(0, 22)
ar1[ar1 %2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [24]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [25]:
#rastgele sayılar
np.random.random(4)

array([0.35721911, 0.56428035, 0.49496249, 0.77914444])

In [26]:
np.random.randint(0, 500, 5)

array([374, 206, 365, 482,   6])

In [27]:
np.random.randint(0, 500, 10)

array([ 52, 332, 442, 232, 440, 109, 322,  30, 303, 127])

In [28]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [29]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [30]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [31]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [32]:
np.random.randint(0, 100, 10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [33]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([5.90946201, 8.92800881, 9.82741611, 6.16176831, 5.41780717,
       8.01774211, 8.64496379, 6.38119414, 8.42653164, 7.58933737])

In [34]:
np.floor(f1)

array([5., 8., 9., 6., 5., 8., 8., 6., 8., 7.])

In [35]:
np.trunc(f1)

array([5., 8., 9., 6., 5., 8., 8., 6., 8., 7.])

In [36]:
f1.astype(int)

array([5, 8, 9, 6, 5, 8, 8, 6, 8, 7])

In [37]:
b2 = np.random.randn(10)
b2

array([ 2.60596728,  0.68350889,  0.30266545,  1.69372293, -1.70608593,
       -1.15911942, -0.13484072,  0.39052784,  0.16690464,  0.18450186])

In [38]:
arr1

array([10, 20, 30, 40, 50, 60])

In [40]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60
