In [1]:
import numpy as np

In [2]:
#matrix powers
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [3]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [4]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [5]:
#Tensor

In [6]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [7]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [8]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [9]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [10]:
S = T1 - T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [11]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [12]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [13]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [14]:
import warnings
warnings.filterwarnings('ignore')

In [15]:
D = T1/T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [16]:
np.__version__

'1.26.4'

In [17]:
np.divide(T1, T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [18]:
#Denklem çözümü (Ax = B)

In [19]:
A = np.array([[1,2,3], [0,1,4], [5,6,0]])
A

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [20]:
C = np.array([[1,2,3], [4,5,6], [7,8,9]])
det_C = np.linalg.det(C)
det_C #det 0 ise matris terslenemez

0.0

In [21]:
B = np.random.random((3,1))
B

array([[0.59912097],
       [0.55373213],
       [0.65719928]])

In [22]:
X = np.dot(np.linalg.inv(A), B)
X

array([[-1.12572833],
       [ 1.04764016],
       [-0.12347701]])

In [23]:
X = np.matmul(np.linalg.inv(A), B)
X

array([[-1.12572833],
       [ 1.04764016],
       [-0.12347701]])

In [24]:
X = np.linalg.inv(A)@B
X

array([[-1.12572833],
       [ 1.04764016],
       [-0.12347701]])

In [25]:
#PANDAS (Python'ın Excel)
import pandas as pd

In [26]:
#Seriler ve Veri Çerçeveleri (DataFrames)

In [27]:
#Seriler
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [28]:
s1.values.itemsize

8

In [29]:
s1.nbytes

56

In [30]:
#Listeden seri oluşturmak
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [31]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [32]:
#Random ve Range fonksiyonlarını kullanarak Seri oluşturma
v2 = np.random.random(10)
ind2 =  np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.40703777, 0.04530539, 0.9034992 , 0.79035128, 0.66030052,
        0.86273225, 0.90309559, 0.56052137, 0.97974753, 0.18532703]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.407038
 1    0.045305
 2    0.903499
 3    0.790351
 4    0.660301
 5    0.862732
 6    0.903096
 7    0.560521
 8    0.979748
 9    0.185327
 dtype: float64)

In [33]:
#Sözlükten (dictionary) seri oluşturmak
"""
ders = {"bina": "A5", "saat": "13.15"}
"""

'\nders = {"bina": "A5", "saat": "13.15"}\n'

In [34]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [35]:
pd.Series(99, index = [0, 1, 2, 3, 4, 5, 6])

0    99
1    99
2    99
3    99
4    99
5    99
6    99
dtype: int64

In [36]:
s[-2:]

8    0.979748
9    0.185327
dtype: float64

In [37]:
s[:-2]

0    0.407038
1    0.045305
2    0.903499
3    0.790351
4    0.660301
5    0.862732
6    0.903096
7    0.560521
dtype: float64

In [38]:
#Append Series
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [39]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [40]:
s4 = s2._append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [41]:
#Atamalı (assignment kullanarak) silme, inplace parametresi ile silme
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [42]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [43]:
s4.drop('a4', inplace = True)

In [44]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [45]:
s4 = s4._append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [46]:
#Atamalı silme
s4 = s4.drop('a4')

In [47]:
#Seriler üzerindeki operasyonlar

In [48]:
v1 = np.array([10, 20, 30])
v2 = np.array([1, 2, 3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [49]:
s1.add(s2)

0    11
1    22
2    33
dtype: int64

In [50]:
s1.sub(s2) #subtract

0     9
1    18
2    27
dtype: int64

In [51]:
s1.mul(s2) #multiply

0    10
1    40
2    90
dtype: int64

In [52]:
s1.div(s2) #divide

0    10.0
1    10.0
2    10.0
dtype: float64

In [53]:
#min(), max(), median(), std()

In [54]:
#Veri saydırma
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [55]:
s5.value_counts()

1    2
2    2
3    2
Name: count, dtype: int64

In [56]:
#DataFrame

In [57]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [58]:
#Python Listesi kullanarak DF oluşturma
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [59]:
rating = [1,2,3,4]
df[1] = rating
#df['kemal'] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [60]:
df.columns = ['Language', 'Rating']
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [61]:
#Sözlükten DF oluşturmak
data = [{'a' : 1, 'b' : 2}, {'a' : 5, 'b' : 10, 'c' : 20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b'])
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])

In [62]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [63]:
df3

a   b
row1  1   2
row2  5  10

In [64]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [65]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [66]:
#Serilerden -sözlükler yardımıyla- DF oluşturma 
mydict = {'A' : pd.Series([1,2,3], index = ['a', 'b', 'c']),
          'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])
         }
df1 = pd.DataFrame(mydict)
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [67]:
#Date Indekslerini kullanarak Rastgele Sayılar yardımıyla DF oluşturmak
dates = pd.date_range(start = '2024-12-24', end = '2024-12-30')
dates

DatetimeIndex(['2024-12-24', '2024-12-25', '2024-12-26', '2024-12-27',
               '2024-12-28', '2024-12-29', '2024-12-30'],
              dtype='datetime64[ns]', freq='D')

In [68]:
dates = pd.date_range('today', periods = 7)
dates

DatetimeIndex(['2024-12-24 18:32:30.968357', '2024-12-25 18:32:30.968357',
               '2024-12-26 18:32:30.968357', '2024-12-27 18:32:30.968357',
               '2024-12-28 18:32:30.968357', '2024-12-29 18:32:30.968357',
               '2024-12-30 18:32:30.968357'],
              dtype='datetime64[ns]', freq='D')

In [69]:
dates = pd.date_range(start = '2024-12-24', periods = 7)
dates

DatetimeIndex(['2024-12-24', '2024-12-25', '2024-12-26', '2024-12-27',
               '2024-12-28', '2024-12-29', '2024-12-30'],
              dtype='datetime64[ns]', freq='D')

In [70]:
M = np.random.random((7,7))
M

array([[0.66747644, 0.57912337, 0.44666505, 0.83990715, 0.53975047,
        0.5241846 , 0.01017418],
       [0.92816792, 0.35183119, 0.64233724, 0.68874112, 0.48001572,
        0.19128624, 0.12191023],
       [0.13819761, 0.25854443, 0.18059112, 0.9926898 , 0.53950935,
        0.63072493, 0.98566215],
       [0.99709168, 0.18601719, 0.28993164, 0.12835269, 0.64134579,
        0.78076943, 0.77170176],
       [0.63844369, 0.61285208, 0.41141465, 0.0119582 , 0.45597384,
        0.50944116, 0.14336616],
       [0.82754686, 0.66333027, 0.99423385, 0.20626706, 0.30803136,
        0.85434198, 0.84897654],
       [0.42299723, 0.09255712, 0.28847356, 0.97701329, 0.85977817,
        0.91911308, 0.08381296]])

In [71]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2024-12-24  0.667476  0.579123  0.446665  0.839907  0.539750  0.524185   
2024-12-25  0.928168  0.351831  0.642337  0.688741  0.480016  0.191286   
2024-12-26  0.138198  0.258544  0.180591  0.992690  0.539509  0.630725   
2024-12-27  0.997092  0.186017  0.289932  0.128353  0.641346  0.780769   
2024-12-28  0.638444  0.612852  0.411415  0.011958  0.455974  0.509441   
2024-12-29  0.827547  0.663330  0.994234  0.206267  0.308031  0.854342   
2024-12-30  0.422997  0.092557  0.288474  0.977013  0.859778  0.919113   

                   6  
2024-12-24  0.010174  
2024-12-25  0.121910  
2024-12-26  0.985662  
2024-12-27  0.771702  
2024-12-28  0.143366  
2024-12-29  0.848977  
2024-12-30  0.083813

In [72]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2024-12-24  0.667476  0.579123  0.446665  0.839907  0.539750  0.524185   
2024-12-25  0.928168  0.351831  0.642337  0.688741  0.480016  0.191286   
2024-12-26  0.138198  0.258544  0.180591  0.992690  0.539509  0.630725   
2024-12-27  0.997092  0.186017  0.289932  0.128353  0.641346  0.780769   
2024-12-28  0.638444  0.612852  0.411415  0.011958  0.455974  0.509441   
2024-12-29  0.827547  0.663330  0.994234  0.206267  0.308031  0.854342   
2024-12-30  0.422997  0.092557  0.288474  0.977013  0.859778  0.919113   

                  C7  
2024-12-24  0.010174  
2024-12-25  0.121910  
2024-12-26  0.985662  
2024-12-27  0.771702  
2024-12-28  0.143366  
2024-12-29  0.848977  
2024-12-30  0.083813

In [73]:
dframe.sort_values(by = 'C1') #ascending (küçükten büyüğe)

C1        C2        C3        C4        C5        C6  \
2024-12-26  0.138198  0.258544  0.180591  0.992690  0.539509  0.630725   
2024-12-30  0.422997  0.092557  0.288474  0.977013  0.859778  0.919113   
2024-12-28  0.638444  0.612852  0.411415  0.011958  0.455974  0.509441   
2024-12-24  0.667476  0.579123  0.446665  0.839907  0.539750  0.524185   
2024-12-29  0.827547  0.663330  0.994234  0.206267  0.308031  0.854342   
2024-12-25  0.928168  0.351831  0.642337  0.688741  0.480016  0.191286   
2024-12-27  0.997092  0.186017  0.289932  0.128353  0.641346  0.780769   

                  C7  
2024-12-26  0.985662  
2024-12-30  0.083813  
2024-12-28  0.143366  
2024-12-24  0.010174  
2024-12-29  0.848977  
2024-12-25  0.121910  
2024-12-27  0.771702

In [74]:
#descending (büyükten küçüğe)
dframe.sort_values(by = 'C1', ascending = False)

C1        C2        C3        C4        C5        C6  \
2024-12-27  0.997092  0.186017  0.289932  0.128353  0.641346  0.780769   
2024-12-25  0.928168  0.351831  0.642337  0.688741  0.480016  0.191286   
2024-12-29  0.827547  0.663330  0.994234  0.206267  0.308031  0.854342   
2024-12-24  0.667476  0.579123  0.446665  0.839907  0.539750  0.524185   
2024-12-28  0.638444  0.612852  0.411415  0.011958  0.455974  0.509441   
2024-12-30  0.422997  0.092557  0.288474  0.977013  0.859778  0.919113   
2024-12-26  0.138198  0.258544  0.180591  0.992690  0.539509  0.630725   

                  C7  
2024-12-27  0.771702  
2024-12-25  0.121910  
2024-12-29  0.848977  
2024-12-24  0.010174  
2024-12-28  0.143366  
2024-12-30  0.083813  
2024-12-26  0.985662

In [75]:
#Satır silme
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10,100,30)
df10 = pd.DataFrame({"C1" : col1, "C2" : col2})
df10

C1  C2
0    10.000000  82
1    13.103448  84
2    16.206897  58
3    19.310345  29
4    22.413793  67
5    25.517241  15
6    28.620690  38
7    31.724138  83
8    34.827586  11
9    37.931034  24
10   41.034483  39
11   44.137931  57
12   47.241379  60
13   50.344828  93
14   53.448276  27
15   56.551724  26
16   59.655172  48
17   62.758621  10
18   65.862069  92
19   68.965517  24
20   72.068966  59
21   75.172414  80
22   78.275862  28
23   81.379310  72
24   84.482759  20
25   87.586207  33
26   90.689655  51
27   93.793103  41
28   96.896552  28
29  100.000000  52

In [76]:
df10 = df10.drop([17,18,19], axis = 0)
df10

C1  C2
0    10.000000  82
1    13.103448  84
2    16.206897  58
3    19.310345  29
4    22.413793  67
5    25.517241  15
6    28.620690  38
7    31.724138  83
8    34.827586  11
9    37.931034  24
10   41.034483  39
11   44.137931  57
12   47.241379  60
13   50.344828  93
14   53.448276  27
15   56.551724  26
16   59.655172  48
20   72.068966  59
21   75.172414  80
22   78.275862  28
23   81.379310  72
24   84.482759  20
25   87.586207  33
26   90.689655  51
27   93.793103  41
28   96.896552  28
29  100.000000  52

In [77]:
df10.drop([16], axis = 0, inplace = True)
df10

C1  C2
0    10.000000  82
1    13.103448  84
2    16.206897  58
3    19.310345  29
4    22.413793  67
5    25.517241  15
6    28.620690  38
7    31.724138  83
8    34.827586  11
9    37.931034  24
10   41.034483  39
11   44.137931  57
12   47.241379  60
13   50.344828  93
14   53.448276  27
15   56.551724  26
20   72.068966  59
21   75.172414  80
22   78.275862  28
23   81.379310  72
24   84.482759  20
25   87.586207  33
26   90.689655  51
27   93.793103  41
28   96.896552  28
29  100.000000  52

In [78]:
#İlk 3 satırı silme
df10 = df10.iloc[3:,]
df10

C1  C2
3    19.310345  29
4    22.413793  67
5    25.517241  15
6    28.620690  38
7    31.724138  83
8    34.827586  11
9    37.931034  24
10   41.034483  39
11   44.137931  57
12   47.241379  60
13   50.344828  93
14   53.448276  27
15   56.551724  26
20   72.068966  59
21   75.172414  80
22   78.275862  28
23   81.379310  72
24   84.482759  20
25   87.586207  33
26   90.689655  51
27   93.793103  41
28   96.896552  28
29  100.000000  52

In [79]:
df10 = df10.iloc[:-2,]
df10

C1  C2
3   19.310345  29
4   22.413793  67
5   25.517241  15
6   28.620690  38
7   31.724138  83
8   34.827586  11
9   37.931034  24
10  41.034483  39
11  44.137931  57
12  47.241379  60
13  50.344828  93
14  53.448276  27
15  56.551724  26
20  72.068966  59
21  75.172414  80
22  78.275862  28
23  81.379310  72
24  84.482759  20
25  87.586207  33
26  90.689655  51
27  93.793103  41

In [80]:
df10.drop(df10.index[df10['C2'] == 33].tolist(), axis = 0, inplace = True)
df10

C1  C2
3   19.310345  29
4   22.413793  67
5   25.517241  15
6   28.620690  38
7   31.724138  83
8   34.827586  11
9   37.931034  24
10  41.034483  39
11  44.137931  57
12  47.241379  60
13  50.344828  93
14  53.448276  27
15  56.551724  26
20  72.068966  59
21  75.172414  80
22  78.275862  28
23  81.379310  72
24  84.482759  20
26  90.689655  51
27  93.793103  41